project:
  type: website

website:
  title: "Thomas Hazell"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: cv.qmd
        text: My CV
      - href: photos.qmd
        text: Photos
    right:
      - icon: twitter
        href: https://x.com/_TomHazell
      - icon: github
        href: https://github.com/T-Hazell
      - icon: mortarboard-fill
        href: https://www.politics.ox.ac.uk/person/thomas-hazell


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

