project:
  type: website
  resources:
    - "papers/*.pdf"

website:
  title: "Thomas Hazell"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: cv.qmd
        text: My CV
      - href: research.qmd
        text: Research
      - href: photos.qmd
        text: Photos
    right:
      - text: "{{< iconify fa6-brands:bluesky >}}"
        href: https://bsky.app/profile/thomashazell.bsky.social
      - icon: github
        href: https://github.com/T-Hazell
      - icon: mortarboard-fill
        href: https://www.politics.ox.ac.uk/person/thomas-hazell


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

