project:
  type: website

website:
  title: "Thomas Hazell"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: cv.qmd
        text: My CV
      - href: photos.qmd
        text: Photos

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

